//! FFI bindings for Everything SDK 3.0
//!
//! This crate provides raw FFI bindings to the Everything SDK 3.0.
//! These bindings are automatically generated by bindgen.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
